// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgn6S2rc76iAkiLKc1EjHDRjTVz6VptUM',
    appId: '1:814148375402:web:e82818e15cb824afd04b13',
    messagingSenderId: '814148375402',
    projectId: 'build4all-manager',
    authDomain: 'build4all-manager.firebaseapp.com',
    storageBucket: 'build4all-manager.firebasestorage.app',
    measurementId: 'G-ERP8SEL3GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDqW3CLN-nNo_e-Vi-9hV5m5Cn0lSuf2U',
    appId: '1:814148375402:android:b84ef37978e1b810d04b13',
    messagingSenderId: '814148375402',
    projectId: 'build4all-manager',
    storageBucket: 'build4all-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7sV_SjVelnMhnm2GUs3RFFunuGLwWgdc',
    appId: '1:814148375402:ios:5ce59e24775a248ed04b13',
    messagingSenderId: '814148375402',
    projectId: 'build4all-manager',
    storageBucket: 'build4all-manager.firebasestorage.app',
    iosBundleId: 'com.build4alluat.build4allmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7sV_SjVelnMhnm2GUs3RFFunuGLwWgdc',
    appId: '1:814148375402:ios:5ce59e24775a248ed04b13',
    messagingSenderId: '814148375402',
    projectId: 'build4all-manager',
    storageBucket: 'build4all-manager.firebasestorage.app',
    iosBundleId: 'com.build4alluat.build4allmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgn6S2rc76iAkiLKc1EjHDRjTVz6VptUM',
    appId: '1:814148375402:web:6e55f97ae2ebe149d04b13',
    messagingSenderId: '814148375402',
    projectId: 'build4all-manager',
    authDomain: 'build4all-manager.firebaseapp.com',
    storageBucket: 'build4all-manager.firebasestorage.app',
    measurementId: 'G-KERJ15LNP8',
  );

}